### ISSUE TITLE
libGLX.so.0 not found

### ISSUE THREAD

**Issue by ShioriMina** [hbiyik/hw_necromancer#4]
I freshly installed ArchLinuxARM, and used the PKGBUILD file in this repository to build `mesa-panfork-git` package,

And installed GNOME DE, but when I open some applications, such as telegram-desktop and gnome-calendar,

When I tried to open these applications, I got `libGLX.so.0: Not found` ERROR

I checked and this file is indeed do not exist, but there is `libOpenGLX`.so under `/usr/lib/`, so I tried to create a symlink,

But I found that the `libOpenGLX.so` symlink is also pointed to a non-exist file.

**Comment by hbiyik** [comment]
Thnaks for the report

should be fixed in: https://github.com/hbiyik/hw_necromancer/commit/02a08eee7e213b243442643156c6b4ec0f44cd63

**Comment by hbiyik** [comment]
fixed in latest AUR build
