### ISSUE TITLE
Outdated comments about patches in linux-rk3588-midstream PKGBUILD

### ISSUE THREAD

**Issue by Googulator** [hbiyik/hw_necromancer#6]
The PKGBUILD file for the midstream kernel references patches that are used when building BSP kernels, but which are useless for 6.x and beyond.

**Comment by hbiyik** [comment]
fixed in https://github.com/hbiyik/hw_necromancer/commit/73a1a89ea630244943ee8151222257c2094c871d

Those were comments only from the previous legecay kernel scripts, there was no actual patching

**Comment by hbiyik** [comment]
Oh thanks for the input btw.
